### ISSUE TITLE
Bosconian (unoffical) (19xx)(Doujin - Sth-Mai) - Sound Board II not detected

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/PC88_MiSTer#11]
The issue is printed on the screen:

![20240804_221203-screen](https://github.com/user-attachments/assets/e24c383c-bf95-4b5c-b8c8-2f6780693cd8)

Thanks

**Comment by yosinda** [comment]
This software appears to be the type that reads the version number of the BASIC ROM and statically selects the port on which Sound Board 2 will be placed.

In the current implementation, Sound Board 2 is connected to an IO port on the on-board sound card.
This follows Puu-san's implementation.

If boot.rom is a PC-8801mk2SR ROM, this software searches for an IO port of the expansion slot, so it cannot find Sound board 2.

This problem can be solved by implementing an on-board sound board (OPN) + expansion sound board 2 (OPNA), just like the actual PC-8801mk2 SR.
However, in this case, the ROM of the model equipped with on-board sound board 2 cannot be used as boot.rom.

What would be the best way to fix this...

**Comment by wwark** [comment]
Thank you for your quick response and the detail of this issue.

If we use extra boot.rom's.... (like PSX core boot1.rom, boot2.rom, and boot3.rom used depending on the region) and load different ones depending switch in OSD, could help the way to fix this issue ?

:+1:

**Comment by wwark** [comment]
It is working great ! Thanks ^^
![20240809_184412-screen](https://github.com/user-attachments/assets/59a74ef1-1745-41f6-a6bb-807d0907b433)

I will prepare a section on the readme for this new option on the OSD.
By the way with this version I can load again games with a MiSTer with SDRAM 2.5
