### ISSUE TITLE
Mugen Senshi Valis 2 (1989)(Nihon Telenet) - opening voice issue

### ISSUE THREAD

**Issue by saebaryo** [MiSTer-devel/PC88_MiSTer#26]
Single SDRAM v3.00 128MB
PC88_unstable_20241214_1372d9

Mode : N88V2
Speed : 8Mhz
Sound Board 2: Expansion

![image](https://github.com/user-attachments/assets/eefa416d-3cab-4a4c-82e0-a42976ea8a7b)

![image](https://github.com/user-attachments/assets/5b376dc4-489e-4aa0-95cd-45892e4f5f22)

![image](https://github.com/user-attachments/assets/f6f1080e-27eb-41d9-ac71-839ada1129b1)

As shown in the screenshot above, after loading PCM data, the opening has a strange sound for voice.

The video is as follows.

https://github.com/user-attachments/assets/e2aa11e5-f1d8-4e37-a3a2-9d38447c458f

The expected voice sound is as shown in the video below.
https://youtu.be/n_tI-NnnKTU?t=82

**Comment by wwark** [comment]
It is fixed with the last update of 12/27/2024 !

**Comment by saebaryo** [comment]
- PC88_unstable_20241227_1047c1
Fixed.
Thank you Yosinda 👍

https://github.com/user-attachments/assets/8c2c784c-e384-469e-b61e-5507c46fe48e
